version: '3.7'
services:
  server:
    image: tablee/code-push-server:v0.5.2
    volumes:
      - data-storage:/data/storage
      - data-tmp:/data/tmp
      - ./config.js:/config.js
    environment:
      DOWNLOAD_URL: 'http://10.1.1.125:3000/download'
      MYSQL_HOST: db
      MYSQL_PORT: '3306'
      MYSQL_USERNAME: 'codepush'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'codepush'
      STORAGE_DIR: '/data/storage'
      DATA_DIR: '/data/tmp'
      NODE_ENV: 'production'
      CONFIG_FILE: '/config.js'
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7.23
    volumes:
      - data-mysql:/var/lib/mysql
      - ./sql/codepush-all.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'On'
  redis:
    image: redis:4.0.11-alpine
    volumes:
      - data-redis:/data

volumes:
  data-storage:
  data-tmp:
  data-mysql:
  data-redis:
